import { Branch, Talent } from "@/types/holo";
import { IDictionary } from "@/types/utils";

const BASE_URL = "https://schedule.hololive.tv";

export const TIMEZONE = "Europe/Zurich";

export const BRANCHES: IDictionary<Branch> = {
  all: {
    apiUrl: `${BASE_URL}/api/list`,
    name: "All talents",
  },
  en: {
    apiUrl: `${BASE_URL}/api/list/8`,
    name: "Hololive EN",
  },
  jp: {
    apiUrl: `${BASE_URL}/api/list/2`,
    name: "Hololive JP",
  },
  id: {
    apiUrl: `${BASE_URL}/api/list/6`,
    name: "Hololive ID",
  },
  stars: {
    apiUrl: `${BASE_URL}/api/list/10`,
    name: "Holostars",
  },
  stars_jp: {
    apiUrl: `${BASE_URL}/api/list/3`,
    name: "Holostars JP",
  },
  stars_en: {
    apiUrl: `${BASE_URL}/api/list/9`,
    name: "Holostars EN",
  },
};

export function getTalent(name: string) {
  const result = TALENTS.find((talent) => talent.apiName === name);
  if (!result) {
    console.error("Could not find talent", name);
  }
  return result;
}

const TALENTS: Talent[] = [
  // -- JP --
  // gen 0
  { apiName: "ときのそら", nickname: "Sora", active: true },
  { apiName: "ロボ子さん", nickname: "Roboco", active: true },
  { apiName: "AZKi", nickname: "AZKi", active: true },
  { apiName: "さくらみこ", nickname: "Miko", active: true },
  { apiName: "星街すいせい", nickname: "Suisei", active: true },
  // 1st gen
  { apiName: "アキロゼ", nickname: "Aki", active: true },
  { apiName: "赤井はあと", nickname: "Haachama", active: true },
  { apiName: "白上フブキ", nickname: "Fubuki", active: true },
  { apiName: "夏色まつり", nickname: "Matsuri", active: true },
  // 2nd gen
  { apiName: "湊あくあ", nickname: "Aqua", active: true },
  { apiName: "紫咲シオン", nickname: "Shion", active: true },
  { apiName: "百鬼あやめ", nickname: "Ayame", active: true },
  { apiName: "癒月ちょこ", nickname: "Choco", active: true },
  { apiName: "大空スバル", nickname: "Subaru", active: true },
  // Gamers
  { apiName: "大神ミオ", nickname: "Mio", active: true },
  { apiName: "猫又おかゆ", nickname: "Okayu", active: true },
  { apiName: "戌神ころね", nickname: "Korone", active: true },
  // holofantasy (3rd)
  { apiName: "兎田ぺこら", nickname: "Pekora", active: true },
  { apiName: "不知火フレア", nickname: "Flare", active: true },
  { apiName: "白銀ノエル", nickname: "Noel", active: true },
  { apiName: "宝鐘マリン", nickname: "Marine", active: true },
  // holoforce (4th)
  { apiName: "天音かなた", nickname: "Kanata", active: true },
  { apiName: "角巻わため", nickname: "Watame", active: true },
  { apiName: "常闇トワ", nickname: "Towa", active: true },
  { apiName: "姫森ルーナ", nickname: "Luna", active: true },
  { apiName: "桐生ココ", nickname: "Coco", active: false },
  // NePoLaBo (5th gen)
  { apiName: "雪花ラミィ", nickname: "Lamy", active: true },
  { apiName: "桃鈴ねね", nickname: "Nenechi", active: true },
  { apiName: "獅白ぼたん", nickname: "Botan", active: true },
  { apiName: "尾丸ポルカ", nickname: "Polka", active: true },
  // holoX
  { apiName: "ラプラス", nickname: "La+", active: true },
  { apiName: "鷹嶺ルイ", nickname: "Lui", active: true },
  { apiName: "博衣こより", nickname: "Koyori", active: true },
  { apiName: "沙花叉クロヱ", nickname: "Chloe", active: true },
  { apiName: "風真いろは", nickname: "Iroha", active: true },
  // -- DEV_IS --
  // ReGLOSS
  { apiName: "火威青", nickname: "Ao", active: true },
  { apiName: "音乃瀬奏", nickname: "Kanade", active: true },
  { apiName: "一条莉々華", nickname: "Ririka", active: true },
  { apiName: "儒烏風亭らでん", nickname: "Raden", active: true },
  { apiName: "轟はじめ", nickname: "Hajime", active: true },
  // -- EN --
  // Myth
  {
    apiName: "Gura",
    nickname: "Gura",
    name: "Gawr Gura",
    twitterAccount: "gawrgura",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Myth",
    generationId: 1,
    active: true,
    colors: {
      light: "#5D81C7",
      dark: "#3A69B2",
    },
  },
  {
    apiName: "Calli",
    nickname: "Calli",
    name: "Mori Calliope",
    twitterAccount: "moricalliope",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Myth",
    generationId: 1,
    active: true,
    colors: {
      light: "#C90D40",
      dark: "#A1020B",
    },
  },
  {
    apiName: "Ina",
    nickname: "Ina",
    name: "Ninomae Ina'nis",
    twitterAccount: "ninomaeinanis",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Myth",
    generationId: 1,
    active: true,
    colors: {
      light: "#62567E",
      dark: "#3F3E69",
    },
  },
  {
    apiName: "Kiara",
    nickname: "Kiara",
    name: "Takanashi Kiara",
    twitterAccount: "takanashikiara",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Myth",
    generationId: 1,
    active: true,
    colors: {
      light: "#FF511C",
      dark: "#DC3907",
    },
  },
  {
    apiName: "Amelia",
    nickname: "Ame",
    name: "Watson Amelia",
    twitterAccount: "watsonameliaEN",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Myth",
    generationId: 1,
    active: true,
    colors: {
      light: "#F8DB92",
      dark: "#F2BD36",
    },
  },
  // Promise
  {
    apiName: "Fauna",
    nickname: "Fauna",
    name: "Ceres Fauna",
    twitterAccount: "ceresfauna",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Promise (former Council)",
    generationId: 2,
    active: true,
    colors: {
      light: "#B4E4C7",
      dark: "#33CA66",
    },
  },
  {
    apiName: "Baelz",
    nickname: "Bae",
    name: "Hakos Baelz",
    twitterAccount: "hakosbaelz",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Promise (former Council)",
    generationId: 2,
    active: true,
    colors: {
      light: "#FF938D",
      dark: "#FE3A2D",
    },
  },
  {
    apiName: "IRyS",
    nickname: "IRyS",
    name: "IRyS",
    twitterAccount: "irys_en",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Promise (former Project: HOPE)",
    generationId: 2,
    active: true,
    colors: {
      light: "#E10E5B",
      dark: "#991150",
    },
  },
  {
    apiName: "Mumei",
    nickname: "Mumei",
    name: "Nanashi Mumei",
    twitterAccount: "nanashimumei_en",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Promise (former Council)",
    generationId: 2,
    active: true,
    colors: {
      light: "#DCC4B2",
      dark: "#C29371",
    },
  },
  {
    apiName: "Kronii",
    nickname: "Kronii",
    name: "Ouro Kronii",
    twitterAccount: "ourokronii",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Promise (former Council)",
    generationId: 2,
    active: true,
    colors: {
      light: "#6879C7",
      dark: "#1D1797",
    },
  },
  {
    apiName: "Sana",
    nickname: "Sana",
    name: "Tsukumo Sana",
    twitterAccount: "tsukumosana",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Council",
    generationId: 2,
    active: false,
    colors: {
      light: "#E7BBD2",
      dark: "#D583AB",
    },
  },
  // Advent
  {
    apiName: "Shiori",
    nickname: "Shiorin",
    name: "Shiori Novella",
    twitterAccount: "shiorinovella",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Advent",
    generationId: 3,
    active: true,
    colors: {
      light: "#B8A0CD",
      dark: "#8C80AE",
    },
  },
  {
    apiName: "Bijou",
    nickname: "Biboo",
    name: "Koseki Bijou",
    twitterAccount: "kosekibijou",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Advent",
    generationId: 3,
    active: true,
    colors: {
      light: "#6E5BF4",
      dark: "#4B43DF",
    },
  },
  {
    apiName: "Nerissa",
    nickname: "Nerissa",
    name: "Nerissa Ravencroft",
    twitterAccount: "nerissa_en",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Advent",
    generationId: 3,
    active: true,
    colors: {
      light: "#2233FB",
      dark: "#1E27AC",
    },
  },
  {
    apiName: "FUWAMOCO",
    nickname: "FUWAMOCO",
    name: "FUWAMOCO",
    twitterAccount: "fuwamoco_en",
    youtubeChannel: "",
    agency: "Hololive EN",
    generation: "Advent",
    generationId: 3,
    active: true,
    colors: {
      light: "#67B2FF",
      dark: "#2D87F7",
    },
  },
  // Justice
  { apiName: "Elizabeth", nickname: "Elizabeth", active: true },
  { apiName: "Gigi", nickname: "Gigi", active: true },
  { apiName: "Cecilia", nickname: "Cecilia", active: true },
  { apiName: "Raora", nickname: "Raora", active: true },
  // -- ID --
  // ID gen 1
  {
    apiName: "Iofi",
    nickname: "Iofi",
    name: "Airani Iofifteen",
    twitterAccount: "airaniiofifteen",
    youtubeChannel: "",
    agency: "Hololive ID",
    generation: "Area 15",
    generationId: 1,
    active: true,
    colors: {
      light: "#B3EE55",
      dark: "#7BDF0E",
    },
  },
  {
    apiName: "Risu",
    nickname: "Risu",
    name: "Ayunda Risu",
    twitterAccount: "ayunda_risu",
    youtubeChannel: "",
    agency: "Hololive ID",
    generation: "Area 15",
    generationId: 1,
    active: true,
    colors: {
      light: "#F6BBBB",
      dark: "#EF8381",
    },
  },
  {
    apiName: "Moona",
    nickname: "Moona",
    name: "Moona Hoshinova",
    twitterAccount: "moonahoshinova",
    youtubeChannel: "",
    agency: "Hololive ID",
    generation: "Area 15",
    generationId: 1,
    active: true,
    colors: {
      light: "#B19DDC",
      dark: "#784DBE",
    },
  },
  // ID gen 2
  {
    apiName: "Anya",
    nickname: "Anya",
    name: "Anya Melfissa",
    twitterAccount: "anyamelfissa",
    youtubeChannel: "",
    agency: "Hololive ID",
    generation: "Holoro",
    generationId: 2,
    active: true,
    colors: {
      light: "#F2C95C",
      dark: "#E89C0F",
    },
  },
  {
    apiName: "Ollie",
    nickname: "Ollie",
    name: "Kureiji Ollie",
    twitterAccount: "kureijiollie",
    youtubeChannel: "",
    agency: "Hololive ID",
    generation: "Holoro",
    generationId: 2,
    active: true,
    colors: {
      light: "#D60E54",
      dark: "#B7030E",
    },
  },
  {
    apiName: "Reine",
    nickname: "Reine",
    name: "Pavolia Reine",
    twitterAccount: "pavoliareine",
    youtubeChannel: "",
    agency: "Hololive ID",
    generation: "Holoro",
    generationId: 2,
    active: true,
    colors: {
      light: "#0F52BA",
      dark: "#040F7F",
    },
  },
  // ID gen 3
  {
    apiName: "Kaela",
    nickname: "Kaela",
    name: "Kaela Kovalskia",
    twitterAccount: "kaelakovalskia",
    youtubeChannel: "",
    agency: "Hololive ID",
    generation: "ID gen 3",
    generationId: 3,
    active: true,
    colors: {
      light: "#FF3D3D",
      dark: "#DC2528",
    },
  },
  {
    apiName: "Kobo",
    nickname: "Kobo",
    name: "Kobo Kanaeru",
    twitterAccount: "kobokanaeru",
    youtubeChannel: "",
    agency: "Hololive ID",
    generation: "ID gen 3",
    generationId: 3,
    active: true,
    colors: {
      light: "#393464",
      dark: "#161C4F",
    },
  },
  {
    apiName: "Zeta",
    nickname: "Zeta",
    name: "Vestia Zeta",
    twitterAccount: "vestiazeta",
    youtubeChannel: "",
    agency: "Hololive ID",
    generation: "ID gen 3",
    generationId: 3,
    active: true,
    colors: {
      light: "#BAB9C3",
      dark: "#97A1AE",
    },
  },
  // -- STARS --
  { apiName: "花咲みやび", nickname: "Miyabi", active: true },
  { apiName: "奏手イヅル", nickname: "Izuru", active: true },
  { apiName: "アルランディス", nickname: "Aruran", active: true },
  { apiName: "律可", nickname: "Rikka", active: true },
  { apiName: "アステル・レダ", nickname: "Astel", active: true },
  { apiName: "岸堂天真", nickname: "Temma", active: true },
  { apiName: "夕刻ロベル", nickname: "Roberu", active: true },
  { apiName: "影山シエン", nickname: "Shien", active: true },
  { apiName: "荒咬オウガ", nickname: "Oga", active: true },
  { apiName: "夜十神封魔", nickname: "Fuma", active: true },
  { apiName: "羽継烏有", nickname: "Uyu", active: true },
  { apiName: "緋崎ガンマ", nickname: "Gamma", active: true },
  { apiName: "水無世燐央", nickname: "Rio", active: true },
  { apiName: "鏡見キラ", nickname: "Kira", active: false },
  // -- STARS EN --
  // TEMPUS HQ
  {
    apiName: "Syrios",
    nickname: "Axel",
    name: "Axel Syrios",
    twitterAccount: "axelsyrios",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS HQ",
    generationId: 1,
    active: true,
    colors: {
      light: "#FF9603",
      dark: "",
    },
  },
  {
    apiName: "Magni",
    nickname: "Magni",
    name: "Magni Dezmond",
    twitterAccount: "magnidezmond",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS HQ",
    generationId: 1,
    active: false,
    colors: {
      light: "#463464",
      dark: "",
    },
  },
  {
    apiName: "Vesper",
    nickname: "Vesper",
    name: "Noir Vesper",
    twitterAccount: "noirvesper_en",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS HQ",
    generationId: 1,
    active: false,
    colors: {
      light: "#C8CCD0",
      dark: "",
    },
  },
  {
    apiName: "Altare",
    nickname: "Altare",
    name: "Regis Altare",
    twitterAccount: "regisaltare",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS HQ",
    generationId: 1,
    active: true,
    colors: {
      light: "#54ACDC",
      dark: "",
    },
  },
  // TEMPUS Vanguard
  {
    apiName: "Hakka",
    nickname: "Hakka",
    name: "Banzoin Hakka",
    twitterAccount: "banzoinhakka",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS Vanguard",
    generationId: 2,
    active: true,
    colors: {
      light: "#C99BF6",
      dark: "",
    },
  },
  {
    apiName: "Bettel",
    nickname: "Bettel",
    name: "Gavis Bettel",
    twitterAccount: "gavisbettel",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS Vanguard",
    generationId: 2,
    active: true,
    colors: {
      light: "#EB3DA2",
      dark: "",
    },
  },
  {
    apiName: "Shinri",
    nickname: "Shinri",
    name: "Josuiji Shinri",
    twitterAccount: "josuijishinri",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS Vanguard",
    generationId: 2,
    active: true,
    colors: {
      light: "#B44D32",
      dark: "",
    },
  },
  {
    apiName: "Flayon",
    nickname: "Flayon",
    name: "Machina X Flayon",
    twitterAccount: "machinaxflayon",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS Vanguard",
    generationId: 2,
    active: true,
    colors: {
      light: "#DD3F34",
      dark: "",
    },
  },
  // TEMPUS ARMIS
  {
    apiName: "Crimzon",
    nickname: "Crimzon",
    name: "Crimzon Ruze",
    twitterAccount: "crimzonruze",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS ARMIS",
    generationId: 3,
    active: true,
    colors: {
      light: "",
      dark: "",
    },
  },
  {
    apiName: "Goldbullet",
    nickname: "Goldbullet",
    name: "Goldbullet",
    twitterAccount: "goldbullet_en",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS ARMIS",
    generationId: 3,
    active: true,
    colors: {
      light: "",
      dark: "",
    },
  },
  {
    apiName: "Jurard",
    nickname: "Jurard",
    name: "Jurard T Rexford",
    twitterAccount: "jurardtrexford",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS ARMIS",
    generationId: 3,
    active: true,
    colors: {
      light: "",
      dark: "",
    },
  },
  {
    apiName: "Octavio",
    nickname: "Octavio",
    name: "Octavio",
    twitterAccount: "octavio_holo",
    youtubeChannel: "",
    agency: "Holostars EN",
    generation: "TEMPUS ARMIS",
    generationId: 3,
    active: true,
    colors: {
      light: "",
      dark: "",
    },
  },
  // -- Staff/misc --
  { apiName: "春先のどか", nickname: "Nodoka", active: true },
  { apiName: "友人A", nickname: "A-chan", active: false },
  { apiName: "ホロライブ", nickname: "Hololive main ch.", active: true },
  { apiName: "ホロスターズ", nickname: "Holostars ch.", active: true },
  { apiName: "HOLOSTARS EN", nickname: "Holostars EN ch.", active: true },
  { apiName: "hololive DEV_IS", nickname: "Hololive DEV_IS ch.", active: true },
  { apiName: "holo EN", nickname: "Hololive EN ch.", active: true },
];
