import { Branch, Talent } from "@/types/holo";
import { IDictionary } from "@/types/utils";

const BASE_URL = "https://schedule.hololive.tv";

export const TIMEZONE = "Europe/Zurich";

export const BRANCHES: IDictionary<Branch> = {
  all: {
    apiUrl: `${BASE_URL}/api/list`,
    pageUrl: "/schedule/all",
    name: "All talents",
  },
  jp: {
    apiUrl: `${BASE_URL}/api/list/2`,
    pageUrl: "/schedule/jp",
    name: "Hololive JP",
  },
  en: {
    apiUrl: `${BASE_URL}/api/list/8`,
    pageUrl: "/schedule/en",
    name: "Hololive EN",
  },
  id: {
    apiUrl: `${BASE_URL}/api/list/6`,
    pageUrl: "/schedule/id",
    name: "Hololive ID",
  },
  stars: {
    apiUrl: `${BASE_URL}/api/list/10`,
    pageUrl: "/schedule/stars",
    name: "Holostars",
  },
  stars_jp: {
    apiUrl: `${BASE_URL}/api/list/3`,
    pageUrl: "/schedule/stars_jp",
    name: "Holostars JP",
  },
  stars_en: {
    apiUrl: `${BASE_URL}/api/list/9`,
    pageUrl: "/schedule/stars_en",
    name: "Holostars EN",
  },
};

export function getTalent(name: string) {
  const result = TALENTS.find((talent) => talent.apiName === name);
  if (!result) {
    console.error("Could not find talent", name);
  }
  return result;
}

export const TALENTS: Talent[] = [
  // -- JP --
  // gen 0
  {
    apiName: "ときのそら",
    nickname: "Sora",
    name: "Tokino Sora",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 0,
    active: true,
  },
  {
    apiName: "ロボ子さん",
    nickname: "Roboco",
    name: "Robocosan",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 0,
    active: true,
  },
  {
    apiName: "AZKi",
    nickname: "AZKi",
    name: "AZKi",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 0,
    active: true,
  },
  {
    apiName: "さくらみこ",
    nickname: "Miko",
    name: "Sakura Miko",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 0,
    active: true,
  },
  {
    apiName: "星街すいせい",
    nickname: "Suisei",
    name: "Hoshimachi Suisei",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 0,
    active: true,
  },
  // 1st gen
  {
    apiName: "アキロゼ",
    nickname: "Aki",
    name: "Aki Rosenthal",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 1,
    active: true,
  },
  {
    apiName: "赤井はあと",
    nickname: "Haachama",
    name: "Akai Haato",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 1,
    active: true,
  },
  {
    apiName: "白上フブキ",
    nickname: "Fubuki",
    name: "Shirakami Fubuki",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 1,
    active: true,
  },
  {
    apiName: "夏色まつり",
    nickname: "Matsuri",
    name: "Natsuiro Matsuri",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 1,
    active: true,
  },
  {
    apiName: "夜空メル",
    nickname: "Mel",
    name: "Yozora Mel",
    fanMark: "🌟",
    agency: "Hololive JP",
    generation: "",
    generationId: 1,
    active: false,
  },
  // 2nd gen
  {
    apiName: "湊あくあ",
    nickname: "Aqua",
    name: "Minato Aqua",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 2,
    active: false,
  },
  {
    apiName: "紫咲シオン",
    nickname: "Shion",
    name: "Murasaki Shion",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 2,
    active: true,
  },
  {
    apiName: "百鬼あやめ",
    nickname: "Ayame",
    name: "Nakiri Ayame",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 2,
    active: true,
  },
  {
    apiName: "癒月ちょこ",
    nickname: "Choco",
    name: "Yuzuki Choco",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 2,
    active: true,
  },
  {
    apiName: "大空スバル",
    nickname: "Subaru",
    name: "Oozora Subaru",
    fanMark: "",
    agency: "Hololive JP",
    generation: "",
    generationId: 2,
    active: true,
  },
  // Gamers
  {
    apiName: "大神ミオ",
    nickname: "Mio",
    name: "Ookami mio",
    fanMark: "",
    agency: "Hololive JP",
    generation: "GAMERS",
    generationId: 2.5, // ????
    active: true,
  },
  {
    apiName: "猫又おかゆ",
    nickname: "Okayu",
    name: "Nekomata Okayu",
    fanMark: "",
    agency: "Hololive JP",
    generation: "GAMERS",
    generationId: 2.5, // ????
    active: true,
  },
  {
    apiName: "戌神ころね",
    nickname: "Korone",
    name: "Inugami Korone",
    fanMark: "",
    agency: "Hololive JP",
    generation: "GAMERS",
    generationId: 2.5, // ????
    active: true,
  },
  // holofantasy (3rd)
  {
    apiName: "兎田ぺこら",
    nickname: "Pekora",
    name: "Usada Pekora",
    fanMark: "",
    agency: "Hololive JP",
    generation: "Fantasy",
    generationId: 3,
    active: true,
  },
  {
    apiName: "不知火フレア",
    nickname: "Flare",
    name: "Shiranui Flare",
    fanMark: "",
    agency: "Hololive JP",
    generation: "Fantasy",
    generationId: 3,
    active: true,
  },
  {
    apiName: "白銀ノエル",
    nickname: "Noel",
    name: "Shirogane Noel",
    fanMark: "",
    agency: "Hololive JP",
    generation: "Fantasy",
    generationId: 3,
    active: true,
  },
  {
    apiName: "宝鐘マリン",
    nickname: "Marine",
    name: "Houshou Marine",
    fanMark: "",
    agency: "Hololive JP",
    generation: "Fantasy",
    generationId: 3,
    active: true,
  },
  {
    apiName: "潤羽るしあ",
    nickname: "Rushia",
    name: "Uruha Rushia",
    fanMark: "",
    agency: "Hololive JP",
    generation: "Fantasy",
    generationId: 3,
    active: false,
  },
  // holoforce (4th)
  {
    apiName: "天音かなた",
    nickname: "Kanata",
    name: "Amane Kanata",
    fanMark: "",
    agency: "Hololive JP",
    generation: "HoloForce",
    generationId: 4,
    active: true,
  },
  {
    apiName: "角巻わため",
    nickname: "Watame",
    name: "Tsunomaki Watame",
    fanMark: "",
    agency: "Hololive JP",
    generation: "HoloForce",
    generationId: 4,
    active: true,
  },
  {
    apiName: "常闇トワ",
    nickname: "Towa",
    name: "Tokoyami Towa",
    fanMark: "",
    agency: "Hololive JP",
    generation: "HoloForce",
    generationId: 4,
    active: true,
  },
  {
    apiName: "姫森ルーナ",
    nickname: "Luna",
    name: "Himemori Luna",
    fanMark: "",
    agency: "Hololive JP",
    generation: "HoloForce",
    generationId: 4,
    active: true,
  },
  {
    apiName: "桐生ココ",
    nickname: "Coco",
    name: "Kiryu Coco",
    fanMark: "",
    agency: "Hololive JP",
    generation: "HoloForce",
    generationId: 4,
    active: false,
  },
  // NePoLaBo (5th gen)
  {
    apiName: "雪花ラミィ",
    nickname: "Lamy",
    name: "Yukihara Lamy",
    fanMark: "☃️",
    agency: "Hololive JP",
    generation: "NePoLaBo",
    generationId: 5,
    active: true,
  },
  {
    apiName: "桃鈴ねね",
    nickname: "Nenechi",
    name: "Momosuzu Nene",
    fanMark: "🍑",
    agency: "Hololive JP",
    generation: "NePoLaBo",
    generationId: 5,
    active: true,
  },
  {
    apiName: "獅白ぼたん",
    nickname: "Botan",
    name: "Shishiro Botan",
    fanMark: "♌",
    agency: "Hololive JP",
    generation: "NePoLaBo",
    generationId: 5,
    active: true,
  },
  {
    apiName: "尾丸ポルカ",
    nickname: "Polka",
    name: "Umaru Polka",
    fanMark: "🎪",
    agency: "Hololive JP",
    generation: "NePoLaBo",
    generationId: 5,
    active: true,
  },
  {
    apiName: "魔乃アロエ",
    nickname: "Aloe",
    name: "Mano Aloe",
    fanMark: "👅",
    agency: "Hololive JP",
    generation: "NePoLaBo",
    generationId: 5,
    active: false,
  },
  // holoX
  {
    apiName: "ラプラス",
    nickname: "La+",
    name: "La+ Darkness",
    fanMark: "",
    agency: "Hololive JP",
    generation: "holoX",
    generationId: 6,
    active: true,
  },
  {
    apiName: "鷹嶺ルイ",
    nickname: "Lui",
    name: "Takane Lui",
    fanMark: "",
    agency: "Hololive JP",
    generation: "holoX",
    generationId: 6,
    active: true,
  },
  {
    apiName: "博衣こより",
    nickname: "Koyori",
    name: "Hakui Koyori",
    fanMark: "",
    agency: "Hololive JP",
    generation: "holoX",
    generationId: 6,
    active: true,
  },
  {
    apiName: "沙花叉クロヱ",
    nickname: "Chloe",
    name: "Sakamata Chloe",
    fanMark: "",
    agency: "Hololive JP",
    generation: "holoX",
    generationId: 6,
    active: true,
  },
  {
    apiName: "風真いろは",
    nickname: "Iroha",
    name: "Kazama Iroha",
    fanMark: "",
    agency: "Hololive JP",
    generation: "holoX",
    generationId: 6,
    active: true,
  },

  // -- DEV_IS --
  // ReGLOSS
  {
    apiName: "火威青",
    nickname: "Ao",
    name: "Hiodoshi Ao",
    fanMark: "",
    twitterAccount: "hiodoshiao",
    youtubeChannel: "HiodoshiAo",
    agency: "Hololive DEV_IS",
    generation: "ReGLOSS",
    generationId: 1,
    active: true,
  },
  {
    apiName: "音乃瀬奏",
    nickname: "Kanade",
    name: "Otonose Kanade",
    fanMark: "",
    twitterAccount: "otonosekanade",
    youtubeChannel: "OtonoseKanade",
    agency: "Hololive DEV_IS",
    generation: "ReGLOSS",
    generationId: 1,
    active: true,
  },
  {
    apiName: "一条莉々華",
    nickname: "Ririka",
    name: "Ichijou Ririka",
    fanMark: "",
    twitterAccount: "ichijouririka",
    youtubeChannel: "IchijouRirika",
    agency: "Hololive DEV_IS",
    generation: "ReGLOSS",
    generationId: 1,
    active: true,
  },
  {
    apiName: "儒烏風亭らでん",
    nickname: "Raden",
    name: "Juufuutei Raden",
    fanMark: "",
    twitterAccount: "juufuuteiraden",
    youtubeChannel: "JuufuuteiRaden",
    agency: "Hololive DEV_IS",
    generation: "ReGLOSS",
    generationId: 1,
    active: true,
  },
  {
    apiName: "轟はじめ",
    nickname: "Hajime",
    name: "Todoroki Hajime",
    fanMark: "",
    twitterAccount: "todoroki_hajime",
    youtubeChannel: "TodorokiHajime",
    agency: "Hololive DEV_IS",
    generation: "ReGLOSS",
    generationId: 1,
    active: true,
  },

  // -- EN --
  // Myth
  {
    apiName: "Gura",
    nickname: "Gura",
    name: "Gawr Gura",
    fanMark: "",
    twitterAccount: "gawrgura",
    youtubeChannel: "GawrGura",
    agency: "Hololive EN",
    generation: "Myth",
    generationId: 1,
    active: true,
    colors: {
      light: "#5D81C7",
      dark: "#3A69B2",
    },
  },
  {
    apiName: "Calli",
    nickname: "Calli",
    name: "Mori Calliope",
    fanMark: "",
    twitterAccount: "moricalliope",
    youtubeChannel: "MoriCalliope",
    agency: "Hololive EN",
    generation: "Myth",
    generationId: 1,
    active: true,
    colors: {
      light: "#C90D40",
      dark: "#A1020B",
    },
  },
  {
    apiName: "Ina",
    nickname: "Ina",
    name: "Ninomae Ina'nis",
    fanMark: "",
    twitterAccount: "ninomaeinanis",
    youtubeChannel: "NinomaeInanis",
    agency: "Hololive EN",
    generation: "Myth",
    generationId: 1,
    active: true,
    colors: {
      light: "#62567E",
      dark: "#3F3E69",
    },
  },
  {
    apiName: "Kiara",
    nickname: "Kiara",
    name: "Takanashi Kiara",
    fanMark: "",
    twitterAccount: "takanashikiara",
    youtubeChannel: "TakanashiKiara",
    agency: "Hololive EN",
    generation: "Myth",
    generationId: 1,
    active: true,
    colors: {
      light: "#FF511C",
      dark: "#DC3907",
    },
  },
  {
    apiName: "Amelia",
    nickname: "Ame",
    name: "Watson Amelia",
    fanMark: "",
    twitterAccount: "watsonameliaEN",
    youtubeChannel: "WatsonAmelia",
    agency: "Hololive EN",
    generation: "Myth",
    generationId: 1,
    active: true, // affiliate
    colors: {
      light: "#F8DB92",
      dark: "#F2BD36",
    },
  },
  // Promise
  {
    apiName: "Fauna",
    nickname: "Fauna",
    name: "Ceres Fauna",
    fanMark: "",
    twitterAccount: "ceresfauna",
    youtubeChannel: "CeresFauna",
    agency: "Hololive EN",
    generation: "Promise",
    generationId: 2,
    active: true,
    colors: {
      light: "#B4E4C7",
      dark: "#33CA66",
    },
  },
  {
    apiName: "Baelz",
    nickname: "Bae",
    name: "Hakos Baelz",
    fanMark: "",
    twitterAccount: "hakosbaelz",
    youtubeChannel: "HakosBaelz",
    agency: "Hololive EN",
    generation: "Promise",
    generationId: 2,
    active: true,
    colors: {
      light: "#FF938D",
      dark: "#FE3A2D",
    },
  },
  {
    apiName: "IRyS",
    nickname: "IRyS",
    name: "IRyS",
    fanMark: "",
    twitterAccount: "irys_en",
    youtubeChannel: "IRyS",
    agency: "Hololive EN",
    generation: "Promise",
    generationId: 2,
    active: true,
    colors: {
      light: "#E10E5B",
      dark: "#991150",
    },
  },
  {
    apiName: "Mumei",
    nickname: "Mumei",
    name: "Nanashi Mumei",
    fanMark: "",
    twitterAccount: "nanashimumei_en",
    youtubeChannel: "NanashiMumei",
    agency: "Hololive EN",
    generation: "Promise",
    generationId: 2,
    active: true,
    colors: {
      light: "#DCC4B2",
      dark: "#C29371",
    },
  },
  {
    apiName: "Kronii",
    nickname: "Kronii",
    name: "Ouro Kronii",
    fanMark: "",
    twitterAccount: "ourokronii",
    youtubeChannel: "OuroKronii",
    agency: "Hololive EN",
    generation: "Promise",
    generationId: 2,
    active: true,
    colors: {
      light: "#6879C7",
      dark: "#1D1797",
    },
  },
  {
    apiName: "Sana",
    nickname: "Sana",
    name: "Tsukumo Sana",
    fanMark: "",
    twitterAccount: "tsukumosana",
    youtubeChannel: "TsukumoSana",
    agency: "Hololive EN",
    generation: "Council",
    generationId: 2,
    active: false,
    colors: {
      light: "#E7BBD2",
      dark: "#D583AB",
    },
  },
  // Advent
  {
    apiName: "Shiori",
    nickname: "Shiorin",
    name: "Shiori Novella",
    fanMark: "",
    twitterAccount: "shiorinovella",
    youtubeChannel: "ShioriNovella",
    agency: "Hololive EN",
    generation: "Advent",
    generationId: 3,
    active: true,
    colors: {
      light: "#B8A0CD",
      dark: "#8C80AE",
    },
  },
  {
    apiName: "Bijou",
    nickname: "Biboo",
    name: "Koseki Bijou",
    fanMark: "",
    twitterAccount: "kosekibijou",
    youtubeChannel: "KosekiBijou",
    agency: "Hololive EN",
    generation: "Advent",
    generationId: 3,
    active: true,
    colors: {
      light: "#6E5BF4",
      dark: "#4B43DF",
    },
  },
  {
    apiName: "Nerissa",
    nickname: "Nerissa",
    name: "Nerissa Ravencroft",
    fanMark: "",
    twitterAccount: "nerissa_en",
    youtubeChannel: "NerissaRavencroft",
    agency: "Hololive EN",
    generation: "Advent",
    generationId: 3,
    active: true,
    colors: {
      light: "#2233FB",
      dark: "#1E27AC",
    },
  },
  {
    apiName: "FUWAMOCO",
    nickname: "FUWAMOCO",
    name: "FUWAMOCO",
    fanMark: "",
    twitterAccount: "fuwamoco_en",
    youtubeChannel: "FUWAMOCOch",
    agency: "Hololive EN",
    generation: "Advent",
    generationId: 3,
    active: true,
    colors: {
      light: "#67B2FF",
      dark: "#2D87F7",
    },
  },
  // Justice
  {
    apiName: "Elizabeth",
    nickname: "Elizabeth",
    name: "Elizabeth Rose Bloodflame",
    fanMark: "",
    twitterAccount: "ERBloodflame",
    youtubeChannel: "holoen_erbloodflame",
    agency: "Hololive EN",
    generation: "Justice",
    generationId: 4,
    active: true,
    colors: {
      light: "#C7383B",
      dark: "#97303A",
    },
  },
  {
    apiName: "Gigi",
    nickname: "Gigi",
    name: "Gigi Murin",
    fanMark: "",
    twitterAccount: "gigimurin",
    youtubeChannel: "holoen_gigimurin",
    agency: "Hololive EN",
    generation: "Justice",
    generationId: 4,
    active: true,
    colors: {
      light: "#FDB440",
      dark: "#CD9328",
    },
  },
  {
    apiName: "Cecilia",
    nickname: "Cecilia",
    name: "Cecilia Immergreen",
    fanMark: "",
    twitterAccount: "ceciliaimgreen",
    youtubeChannel: "holoen_ceciliaimmergreen",
    agency: "Hololive EN",
    generation: "Justice",
    generationId: 4,
    active: true,
    colors: {
      light: "#119A5C",
      dark: "#137A42",
    },
  },
  {
    apiName: "Raora",
    nickname: "Raora",
    name: "Raora Panthera",
    fanMark: "",
    twitterAccount: "raorapanthera",
    youtubeChannel: "holoen_raorapanthera",
    agency: "Hololive EN",
    generation: "Justice",
    generationId: 4,
    active: true,
    colors: {
      light: "#F087A9",
      dark: "#E75786",
    },
  },

  // -- ID --
  // Area 15
  {
    apiName: "Iofi",
    nickname: "Iofi",
    name: "Airani Iofifteen",
    fanMark: "",
    twitterAccount: "airaniiofifteen",
    youtubeChannel: "AiraniIofifteen",
    agency: "Hololive ID",
    generation: "Area 15",
    generationId: 1,
    active: true,
    colors: {
      light: "#B3EE55",
      dark: "#7BDF0E",
    },
  },
  {
    apiName: "Risu",
    nickname: "Risu",
    name: "Ayunda Risu",
    fanMark: "",
    twitterAccount: "ayunda_risu",
    youtubeChannel: "AyundaRisu",
    agency: "Hololive ID",
    generation: "Area 15",
    generationId: 1,
    active: true,
    colors: {
      light: "#F6BBBB",
      dark: "#EF8381",
    },
  },
  {
    apiName: "Moona",
    nickname: "Moona",
    name: "Moona Hoshinova",
    fanMark: "",
    twitterAccount: "moonahoshinova",
    youtubeChannel: "MoonaHoshinova",
    agency: "Hololive ID",
    generation: "Area 15",
    generationId: 1,
    active: true,
    colors: {
      light: "#B19DDC",
      dark: "#784DBE",
    },
  },
  // Holoro
  {
    apiName: "Anya",
    nickname: "Anya",
    name: "Anya Melfissa",
    fanMark: "",
    twitterAccount: "anyamelfissa",
    youtubeChannel: "AnyaMelfissa",
    agency: "Hololive ID",
    generation: "Holoro",
    generationId: 2,
    active: true,
    colors: {
      light: "#F2C95C",
      dark: "#E89C0F",
    },
  },
  {
    apiName: "Ollie",
    nickname: "Ollie",
    name: "Kureiji Ollie",
    fanMark: "",
    twitterAccount: "kureijiollie",
    youtubeChannel: "KureijiOllie",
    agency: "Hololive ID",
    generation: "Holoro",
    generationId: 2,
    active: true,
    colors: {
      light: "#D60E54",
      dark: "#B7030E",
    },
  },
  {
    apiName: "Reine",
    nickname: "Reine",
    name: "Pavolia Reine",
    fanMark: "",
    twitterAccount: "pavoliareine",
    youtubeChannel: "PavoliaReine",
    agency: "Hololive ID",
    generation: "Holoro",
    generationId: 2,
    active: true,
    colors: {
      light: "#0F52BA",
      dark: "#040F7F",
    },
  },
  // HoloH3ro
  {
    apiName: "Kaela",
    nickname: "Kaela",
    name: "Kaela Kovalskia",
    fanMark: "",
    twitterAccount: "kaelakovalskia",
    youtubeChannel: "KaelaKovalskia",
    agency: "Hololive ID",
    generation: "HoloH3ro",
    generationId: 3,
    active: true,
    colors: {
      light: "#FF3D3D",
      dark: "#DC2528",
    },
  },
  {
    apiName: "Kobo",
    nickname: "Kobo",
    name: "Kobo Kanaeru",
    fanMark: "",
    twitterAccount: "kobokanaeru",
    youtubeChannel: "KoboKanaeru",
    agency: "Hololive ID",
    generation: "HoloH3ro",
    generationId: 3,
    active: true,
    colors: {
      light: "#393464",
      dark: "#161C4F",
    },
  },
  {
    apiName: "Zeta",
    nickname: "Zeta",
    name: "Vestia Zeta",
    fanMark: "",
    twitterAccount: "vestiazeta",
    youtubeChannel: "VestiaZeta",
    agency: "Hololive ID",
    generation: "HoloH3ro",
    generationId: 3,
    active: true,
    colors: {
      light: "#BAB9C3",
      dark: "#97A1AE",
    },
  },

  // -- STARS --
  // gen 1
  {
    apiName: "花咲みやび",
    nickname: "Miyabi",
    agency: "Holostars JP",
    generation: "",
    generationId: 1,
    active: true,
  },
  {
    apiName: "奏手イヅル",
    nickname: "Izuru",
    agency: "Holostars JP",
    generation: "",
    generationId: 1,
    active: true,
  },
  {
    apiName: "アルランディス",
    nickname: "Aruran",
    agency: "Holostars JP",
    generation: "",
    generationId: 1,
    active: true,
  },
  {
    apiName: "律可",
    nickname: "Rikka",
    agency: "Holostars JP",
    generation: "",
    generationId: 1,
    active: true,
  },
  {
    apiName: "鏡見キラ",
    nickname: "Kira",
    agency: "Holostars JP",
    generation: "",
    generationId: 1,
    active: false,
  },
  // gen 2
  {
    apiName: "アステル・レダ",
    nickname: "Astel",
    agency: "Holostars JP",
    generation: "SunTempo",
    generationId: 2,
    active: true,
  },
  {
    apiName: "岸堂天真",
    nickname: "Temma",
    agency: "Holostars JP",
    generation: "SunTempo",
    generationId: 2,
    active: true,
  },
  {
    apiName: "夕刻ロベル",
    nickname: "Roberu",
    agency: "Holostars JP",
    generation: "SunTempo",
    generationId: 2,
    active: true,
  },
  // gen 3
  {
    apiName: "影山シエン",
    nickname: "Shien",
    agency: "Holostars JP",
    generation: "MaFia",
    generationId: 3,
    active: true,
  },
  {
    apiName: "荒咬オウガ",
    nickname: "Oga",
    agency: "Holostars JP",
    generation: "MaFia",
    generationId: 3,
    active: true,
  },
  // UPROAR
  {
    apiName: "夜十神封魔",
    nickname: "Fuma",
    agency: "Holostars JP",
    generation: "UPROAR!!",
    generationId: 4,
    active: true,
  },
  {
    apiName: "羽継烏有",
    nickname: "Uyu",
    agency: "Holostars JP",
    generation: "UPROAR!!",
    generationId: 4,
    active: true,
  },
  {
    apiName: "緋崎ガンマ",
    nickname: "Gamma",
    agency: "Holostars JP",
    generation: "UPROAR!!",
    generationId: 4,
    active: false,
  },
  {
    apiName: "水無世燐央",
    nickname: "Rio",
    agency: "Holostars JP",
    generation: "UPROAR!!",
    generationId: 4,
    active: true,
  },

  // -- STARS EN --
  // TEMPUS HQ
  {
    apiName: "Syrios",
    nickname: "Axel",
    name: "Axel Syrios",
    fanMark: "",
    twitterAccount: "axelsyrios",
    youtubeChannel: "AxelSyrios",
    agency: "Holostars EN",
    generation: "TEMPUS HQ",
    generationId: 1,
    active: true,
    colors: {
      light: "#FF9603",
    },
  },
  {
    apiName: "Magni",
    nickname: "Magni",
    name: "Magni Dezmond",
    fanMark: "",
    twitterAccount: "magnidezmond",
    youtubeChannel: "MagniDezmond",
    agency: "Holostars EN",
    generation: "TEMPUS HQ",
    generationId: 1,
    active: false,
    colors: {
      light: "#463464",
    },
  },
  {
    apiName: "Vesper",
    nickname: "Vesper",
    name: "Noir Vesper",
    fanMark: "",
    twitterAccount: "noirvesper_en",
    youtubeChannel: "NoirVesper",
    agency: "Holostars EN",
    generation: "TEMPUS HQ",
    generationId: 1,
    active: false,
    colors: {
      light: "#C8CCD0",
    },
  },
  {
    apiName: "Altare",
    nickname: "Altare",
    name: "Regis Altare",
    fanMark: "",
    twitterAccount: "regisaltare",
    youtubeChannel: "RegisAltare",
    agency: "Holostars EN",
    generation: "TEMPUS HQ",
    generationId: 1,
    active: true,
    colors: {
      light: "#54ACDC",
    },
  },
  // TEMPUS Vanguard
  {
    apiName: "Hakka",
    nickname: "Hakka",
    name: "Banzoin Hakka",
    fanMark: "",
    twitterAccount: "banzoinhakka",
    youtubeChannel: "BanzoinHakka",
    agency: "Holostars EN",
    generation: "TEMPUS Vanguard",
    generationId: 2,
    active: true,
    colors: {
      light: "#C99BF6",
    },
  },
  {
    apiName: "Bettel",
    nickname: "Bettel",
    name: "Gavis Bettel",
    fanMark: "",
    twitterAccount: "gavisbettel",
    youtubeChannel: "GavisBettel",
    agency: "Holostars EN",
    generation: "TEMPUS Vanguard",
    generationId: 2,
    active: true,
    colors: {
      light: "#EB3DA2",
    },
  },
  {
    apiName: "Shinri",
    nickname: "Shinri",
    name: "Josuiji Shinri",
    fanMark: "",
    twitterAccount: "josuijishinri",
    youtubeChannel: "JosuijiShinri",
    agency: "Holostars EN",
    generation: "TEMPUS Vanguard",
    generationId: 2,
    active: true,
    colors: {
      light: "#B44D32",
    },
  },
  {
    apiName: "Flayon",
    nickname: "Flayon",
    name: "Machina X Flayon",
    fanMark: "",
    twitterAccount: "machinaxflayon",
    youtubeChannel: "MachinaXFlayon",
    agency: "Holostars EN",
    generation: "TEMPUS Vanguard",
    generationId: 2,
    active: true,
    colors: {
      light: "#DD3F34",
    },
  },
  // ARMIS
  {
    apiName: "Crimzon",
    nickname: "Crimzon",
    name: "Crimzon Ruze",
    fanMark: "",
    twitterAccount: "crimzonruze",
    youtubeChannel: "CrimzonRuze",
    agency: "Holostars EN",
    generation: "ARMIS",
    generationId: 3,
    active: true,
    colors: {
      light: "#E60012",
    },
  },
  {
    apiName: "Goldbullet",
    nickname: "Goldbullet",
    name: "Goldbullet",
    fanMark: "",
    twitterAccount: "goldbullet_en",
    youtubeChannel: "Goldbulletch",
    agency: "Holostars EN",
    generation: "ARMIS",
    generationId: 3,
    active: true,
    colors: {
      light: "#0A6463",
    },
  },
  {
    apiName: "Jurard",
    nickname: "Jurard",
    name: "Jurard T Rexford",
    fanMark: "",
    twitterAccount: "jurardtrexford",
    youtubeChannel: "JurardTRexford",
    agency: "Holostars EN",
    generation: "ARMIS",
    generationId: 3,
    active: true,
    colors: {
      light: "#383635",
    },
  },
  {
    apiName: "Octavio",
    nickname: "Octavio",
    name: "Octavio",
    fanMark: "",
    twitterAccount: "octavio_holo",
    youtubeChannel: "Octavio_en",
    agency: "Holostars EN",
    generation: "ARMIS",
    generationId: 3,
    active: true,
    colors: {
      light: "#1C449A",
    },
  },

  // -- Staff --
  {
    apiName: "友人A",
    nickname: "A-chan",
    name: "Friend A",
    fanMark: "👓",
    twitterAccount: "achan_UGA",
    youtubeChannel: "hololive",
    agency: "Hololive staff",
    generation: "",
    generationId: 1,
    active: false,
    colors: {
      light: "#483F7A",
      dark: "#2B2B6E",
    },
  },
  {
    apiName: "春先のどか",
    nickname: "Nodoka",
    name: "Harusaki Nodoka",
    fanMark: "📝",
    twitterAccount: "harusakinodoka",
    youtubeChannel: "hololive",
    agency: "Hololive staff",
    generation: "",
    generationId: 2,
    active: true,
    colors: {
      light: "#E3F1CD",
      dark: "#CEE5A2",
    },
  },

  // -- Channels --
  {
    apiName: "ホロライブ",
    nickname: "Hololive main ch.",
    twitterAccount: "hololivetv",
    youtubeChannel: "hololive",
    active: true,
  },
  {
    apiName: "hololive DEV_IS",
    nickname: "Hololive DEV_IS ch.",
    twitterAccount: "",
    youtubeChannel: "hololiveDEV_IS",
    active: true,
  },
  {
    apiName: "holo EN",
    nickname: "Hololive EN ch.",
    twitterAccount: "hololive_En",
    youtubeChannel: "",
    active: true,
  },
  {
    apiName: "ホロスターズ",
    nickname: "Holostars ch.",
    twitterAccount: "",
    youtubeChannel: "",
    active: true,
  },
  {
    apiName: "HOLOSTARS EN",
    nickname: "Holostars EN ch.",
    twitterAccount: "",
    youtubeChannel: "",
    active: true,
  },
];
