name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    uses: steeven9/CICD-template/.github/workflows/docker-build.yml@main
    with:
      image-name: steeven9/holodule-frontend
      push: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
